import { derivAPI } from "./deriv-api.js";

const $ = (id, required = true) => {
  const el = document.getElementById(id);
  if (!el && required) console.warn("Missing required element:", id);
  return el;
};

const ui = {
  estadoConexion: $("estadoConexion"), textoEstado: $("textoEstado"), estadoMotor: $("estadoMotor"),
  botonConectar: $("botonConectar"), botonDesconectar: $("botonDesconectar"), botonEncender: $("botonEncender"), botonAnalizar: $("botonAnalizar"), botonVoz: $("botonVoz"),
  selectorIndice: $("selectorIndice"), selectorOperacion: $("selectorOperacion"), selectorModo: $("selectorModo"),
  nombreIndice: $("nombreIndice"), estadoDatos: $("estadoDatos"), precioActual: $("precioActual"), contadorTicks: $("contadorTicks"), ultimoDigito: $("ultimoDigito"), horaActualizacion: $("horaActualizacion"),
  textoProgreso: $("textoProgreso"), numeroProgreso: $("numeroProgreso"), barraDatos: $("barraDatos"),
  tendencia: $("tendencia"), detalleTendencia: $("detalleTendencia"), rsi: $("rsi"), detalleRsi: $("detalleRsi"), momentum: $("momentum"), detalleMomentum: $("detalleMomentum"), volatilidad: $("volatilidad"), detalleVolatilidad: $("detalleVolatilidad"),
  panelSenal: $("panelSenal"), prediccionEstado: $("prediccionEstado"), prediccionTitulo: $("prediccionTitulo"), prediccionDireccion: $("prediccionDireccion"), prediccionConfianza: $("prediccionConfianza"), barraConfianza: $("barraConfianza"), prediccionMotivos: $("prediccionMotivos"), vigenciaSenal: $("vigenciaSenal"), cuentaRegresiva: $("cuentaRegresiva"),
  selectorVoz: $("selectorVoz"), velocidadVoz: $("velocidadVoz"), tonoVoz: $("tonoVoz"), volumenVoz: $("volumenVoz"), valorVelocidad: $("valorVelocidad"), valorTono: $("valorTono"), valorVolumen: $("valorVolumen"), botonProbarVoz: $("botonProbarVoz"),
  botonLimpiarHistorial: $("botonLimpiarHistorial"), historialAnalisis: $("historialAnalisis"), botonLimpiarRegistro: $("botonLimpiarRegistro"), registroActividad: $("registroActividad")
};

const CFG = { version: "7.0.0", maxTicks: 1000, recentWindow: 30, historyWindow: 1000, countdown: 10, maxHistory: 10 };
const MARKET_NAMES = {"1HZ10V":"Volatility 10 (1s)","1HZ25V":"Volatility 25 (1s)","1HZ50V":"Volatility 50 (1s)","1HZ75V":"Volatility 75 (1s)","1HZ100V":"Volatility 100 (1s)","R_10":"Volatility 10","R_25":"Volatility 25","R_50":"Volatility 50","R_75":"Volatility 75","R_100":"Volatility 100"};
const STRATEGY_NAMES = {rise_fall:"Rise / Fall",even_odd:"Even / Odd",over_under:"Over / Under",match:"Match"};

const state = {
  connected:false, connecting:false, engineOn:false, signalActive:false,
  symbol:"", market:"", strategy:"rise_fall", mode:"fast",
  prices:[], digits:[], ticks:0, previousPrice:null, pipSize:2,
  indicators:null, preparedPrediction:null, history:[],
  voiceOn:true, voices:[], selectedVoice:null, countdownTimer:null
};

function time(epoch = null){const d=Number.isFinite(epoch)?new Date(epoch*1000):new Date();return d.toLocaleTimeString("es-SV",{hour:"2-digit",minute:"2-digit",second:"2-digit"});}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function log(message,type="normal"){const p=document.createElement("p");p.textContent=`[${time()}] ${message}`;if(type!=="normal")p.classList.add(type);ui.registroActividad.prepend(p);while(ui.registroActividad.children.length>60)ui.registroActividad.lastElementChild?.remove();}

function setConnection(status,text){ui.estadoConexion.className=`status-pill ${status}`;ui.textoEstado.textContent=text;state.connected=status==="connected";state.connecting=status==="connecting";ui.botonConectar.disabled=state.connected||state.connecting;ui.botonDesconectar.disabled=!state.connected;ui.botonEncender.disabled=!state.connected;refreshButtons();}
function setEngine(on){state.engineOn=on;ui.estadoMotor.className=`status-pill ${on?"engine-on":"engine-off"}`;ui.estadoMotor.querySelector("strong").textContent=on?"ENGINE ON":"ENGINE OFF";ui.botonEncender.textContent=on?"POWER OFF":"POWER ENGINE";ui.botonEncender.classList.toggle("on",on);if(!on){state.preparedPrediction=null;stopCountdown();resetSignal("Engine is off.");}refreshButtons();}
function refreshButtons(){ui.botonAnalizar.disabled=!(state.connected&&state.engineOn)||state.signalActive;ui.botonAnalizar.textContent=state.signalActive?"SIGNAL ACTIVE":"PREDICTION";}
function syncSelection(){state.symbol=ui.selectorIndice.value;state.market=MARKET_NAMES[state.symbol]||state.symbol;state.strategy=ui.selectorOperacion.value;state.mode=ui.selectorModo.value;ui.nombreIndice.textContent=state.market;}

function populateVoices(){if(!("speechSynthesis" in window))return;const all=window.speechSynthesis.getVoices();state.voices=all.filter(v=>v.lang?.toLowerCase().startsWith("es"));if(!state.voices.length)state.voices=all;const previous=ui.selectorVoz.value;ui.selectorVoz.innerHTML="";state.voices.forEach((v,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=`${v.name} — ${v.lang}`;ui.selectorVoz.appendChild(o);});if(previous&&Number(previous)<state.voices.length)ui.selectorVoz.value=previous;state.selectedVoice=state.voices[Number(ui.selectorVoz.value)||0]||null;}
function stopVoice(){if("speechSynthesis" in window)window.speechSynthesis.cancel();}
function speak(text,{cancel=true,onend=null,rate=null}={}){if(!state.voiceOn||!("speechSynthesis" in window)||!text){onend?.();return;}if(cancel)stopVoice();const u=new SpeechSynthesisUtterance(text);u.lang=state.selectedVoice?.lang||"es-SV";if(state.selectedVoice)u.voice=state.selectedVoice;u.rate=rate??Number(ui.velocidadVoz.value);u.pitch=Number(ui.tonoVoz.value);u.volume=Number(ui.volumenVoz.value);if(onend)u.onend=onend;window.speechSynthesis.speak(u);}
function updateVoiceUi(){ui.botonVoz.textContent=state.voiceOn?"🔊":"🔇";ui.botonVoz.classList.toggle("active",state.voiceOn);ui.botonVoz.setAttribute("aria-pressed",String(state.voiceOn));ui.valorVelocidad.textContent=`${Number(ui.velocidadVoz.value).toFixed(2)}x`;ui.valorTono.textContent=Number(ui.tonoVoz.value).toFixed(1);ui.valorVolumen.textContent=`${Math.round(Number(ui.volumenVoz.value)*100)}%`;}

function average(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:0;}
function std(a){if(a.length<2)return 0;const m=average(a);return Math.sqrt(average(a.map(v=>(v-m)**2)));}
function rsi(prices,period){if(prices.length<period+1)return null;const d=prices.slice(-(period+1));let gains=0,losses=0;for(let i=1;i<d.length;i++){const x=d[i]-d[i-1];if(x>0)gains+=x;else losses+=Math.abs(x);}if(!gains&&!losses)return 50;if(!losses)return 100;const rs=(gains/period)/(losses/period);return 100-100/(1+rs);}
function computeIndicators(){const p=state.prices;if(p.length<2)return null;const fast=state.mode==="fast";const trendN=Math.min(fast?12:30,p.length);const momN=Math.min(fast?5:10,p.length-1);const recent=p.slice(-trendN);const half=Math.max(1,Math.floor(recent.length/2));const a=average(recent.slice(0,half)),b=average(recent.slice(half));const change=a?((b-a)/a)*100:0;const trend=change>0?"BULLISH":change<0?"BEARISH":"SIDEWAYS";const momentum=p.at(-1)-p[p.length-1-momN];const momentumPct=p[p.length-1-momN]?momentum/p[p.length-1-momN]*100:0;const rv=std(recent);const volPct=average(recent)?rv/average(recent)*100:0;return{trend,change,momentum,momentumPct,rsi:rsi(p,fast?8:14),volPct,volLevel:volPct>=.08?"HIGH":volPct>=.025?"MEDIUM":"LOW"};}
function renderIndicators(){state.indicators=computeIndicators();const i=state.indicators;if(!i)return;ui.tendencia.textContent=i.trend;ui.detalleTendencia.textContent=`Change: ${i.change.toFixed(4)}%`;ui.rsi.textContent=Number.isFinite(i.rsi)?i.rsi.toFixed(1):"--";ui.detalleRsi.textContent=!Number.isFinite(i.rsi)?"Collecting data":i.rsi>70?"High zone":i.rsi<30?"Low zone":"Neutral zone";ui.momentum.textContent=i.momentum>0?"POSITIVE":i.momentum<0?"NEGATIVE":"NEUTRAL";ui.detalleMomentum.textContent=`${i.momentum.toFixed(5)} · ${i.momentumPct.toFixed(4)}%`;ui.volatilidad.textContent=`${i.volPct.toFixed(4)}%`;ui.detalleVolatilidad.textContent=`${i.volLevel} level`;}

function digitStats(list){const counts=Array(10).fill(0);list.forEach(d=>{if(Number.isInteger(d))counts[d]++});return{counts,total:list.length,pct:counts.map(c=>list.length?c/list.length*100:0)};}
function confidence(score){return Math.round(clamp(score,45,90));}
function basePrediction(direction,conf,reasons,warnings=[]){return{direction,confidence:direction==="NO RECOMMENDED"?45:confidence(conf),reasons,warnings,time:time(),market:state.market,strategy:STRATEGY_NAMES[state.strategy]};}
function predictRiseFall(){const i=state.indicators||computeIndicators();if(!i)return basePrediction("NO RECOMMENDED",45,[],["The engine is collecting the first market movements."]);let score=0,reasons=[],warnings=[];if(i.trend==="BULLISH"){score+=28;reasons.push("Trend is bullish.");}else if(i.trend==="BEARISH"){score-=28;reasons.push("Trend is bearish.");}else warnings.push("Trend is sideways.");if(i.momentum>0){score+=24;reasons.push("Momentum is positive.");}else if(i.momentum<0){score-=24;reasons.push("Momentum is negative.");}if(Number.isFinite(i.rsi)){if(i.rsi>=55&&i.rsi<=72){score+=28;reasons.push(`RSI ${i.rsi.toFixed(1)} confirms bullish pressure.`);}else if(i.rsi<=45&&i.rsi>=28){score-=28;reasons.push(`RSI ${i.rsi.toFixed(1)} confirms bearish pressure.`);}else if(i.rsi>72){score-=10;warnings.push("RSI is high; movement may be exhausted.");}else if(i.rsi<28){score+=10;warnings.push("RSI is low; a rebound is possible.");}else warnings.push("RSI is neutral.");}if(i.volLevel==="LOW"){reasons.push("Volatility is stable.");}else if(i.volLevel==="HIGH"){warnings.push("High volatility lowers signal stability.");score*=.8;}const direction=score>=45?"RISE":score<=-45?"FALL":"NO RECOMMENDED";return basePrediction(direction,direction==="NO RECOMMENDED"?45:55+Math.abs(score)*.38,reasons,warnings.concat(direction==="NO RECOMMENDED"?["RSI, momentum and trend do not agree strongly enough."]:[]));}
function predictDigits(){const recent=state.digits.slice(-CFG.recentWindow),history=state.digits.slice(-CFG.historyWindow);if(!recent.length)return basePrediction("NO RECOMMENDED",45,[],["The engine is waiting for the first digit."]);const rs=digitStats(recent),hs=digitStats(history),reasons=[],warnings=[];if(state.strategy==="even_odd"){const re=recent.filter(d=>d%2===0).length/recent.length,he=history.filter(d=>d%2===0).length/history.length,blend=re*.75+he*.25,d=blend>=.58?"EVEN":blend<=.42?"ODD":"NO RECOMMENDED";reasons.push(`Recent even digits: ${(re*100).toFixed(1)}%.`,`Historical even digits: ${(he*100).toFixed(1)}%.`);if(d==="NO RECOMMENDED")warnings.push("Even and odd distribution is too balanced.");return basePrediction(d,d==="NO RECOMMENDED"?45:55+Math.abs(blend-.5)*180,reasons,warnings);}
if(state.strategy==="over_under"){const ro=recent.filter(d=>d>=5).length/recent.length,ho=history.filter(d=>d>=5).length/history.length,blend=ro*.75+ho*.25,d=blend>=.58?"OVER":blend<=.42?"UNDER":"NO RECOMMENDED";reasons.push(`Recent digits 5–9: ${(ro*100).toFixed(1)}%.`,`Historical digits 5–9: ${(ho*100).toFixed(1)}%.`);if(d==="NO RECOMMENDED")warnings.push("High and low digit distribution is too balanced.");return basePrediction(d,d==="NO RECOMMENDED"?45:55+Math.abs(blend-.5)*180,reasons,warnings);}
let best=0,bestScore=-1;for(let d=0;d<10;d++){const s=rs.pct[d]*.75+hs.pct[d]*.25;if(s>bestScore){best=d;bestScore=s;}}const advantage=bestScore-10;const direction=advantage>=3&&rs.counts[best]>=Math.max(2,Math.ceil(recent.length*.14))?`MATCH ${best}`:"NO RECOMMENDED";reasons.push(`Digit ${best} appeared ${rs.counts[best]} times in the last ${recent.length} ticks.`,`Recent frequency: ${rs.pct[best].toFixed(1)}%.`,`Historical frequency: ${hs.pct[best].toFixed(1)}%.`);if(direction==="NO RECOMMENDED")warnings.push("No digit has a strong enough recent and historical advantage.");return basePrediction(direction,direction==="NO RECOMMENDED"?45:58+advantage*4,reasons,warnings);}
function buildPrediction(){return state.strategy==="rise_fall"?predictRiseFall():predictDigits();}
function updateEngine(){if(!state.engineOn||!state.connected)return;state.preparedPrediction=buildPrediction();}

function renderProgress(){const n=state.prices.length;ui.numeroProgreso.textContent=`${n}/${CFG.maxTicks}`;ui.barraDatos.style.width=`${Math.min(100,n/CFG.maxTicks*100)}%`;ui.textoProgreso.textContent=!state.connected?"CONNECT TO START":!state.engineOn?"CONNECTED · ENGINE OFF":n<30?"LIVE ANALYSIS · BUILDING CONTEXT":n<1000?"LIVE ANALYSIS · EXPANDING MEMORY":"LIVE ANALYSIS · FULL MEMORY";}
function resetSignal(message="Connect and power the engine."){ui.panelSenal.className="signal-panel neutral";ui.prediccionEstado.textContent=state.engineOn?"READY":"ENGINE OFF";ui.prediccionTitulo.textContent=state.engineOn?"Prediction prepared in background":"Waiting for engine";ui.prediccionDireccion.textContent="--";ui.prediccionConfianza.textContent="--";ui.barraConfianza.style.width="0%";ui.prediccionMotivos.innerHTML=`<li>${message}</li>`;ui.vigenciaSenal.textContent="No active signal";ui.cuentaRegresiva.textContent="--";}
function renderPrediction(p){const no=p.direction==="NO RECOMMENDED";ui.panelSenal.className=`signal-panel ${no?"bad":p.direction==="FALL"||p.direction==="ODD"||p.direction==="UNDER"?"bad":"good"}`;ui.prediccionEstado.textContent=no?"NO RECOMMENDED":"PREDICTION READY";ui.prediccionTitulo.textContent=no?"Wait for a stronger setup":"Technical signal detected";ui.prediccionDireccion.textContent=p.direction;ui.prediccionConfianza.textContent=`${p.confidence}%`;ui.barraConfianza.style.width=`${p.confidence}%`;ui.prediccionMotivos.innerHTML="";[...p.reasons,...p.warnings.map(w=>`⚠ ${w}`)].forEach(t=>{const li=document.createElement("li");li.textContent=t;ui.prediccionMotivos.appendChild(li)});ui.vigenciaSenal.textContent=no?"Wait for a new opportunity":`You have ${CFG.countdown} seconds to place the operation.`;ui.cuentaRegresiva.textContent=no?"--":String(CFG.countdown);}
function addHistory(p){state.history.unshift(p);state.history=state.history.slice(0,CFG.maxHistory);ui.historialAnalisis.innerHTML="";state.history.forEach(x=>{const a=document.createElement("article");a.innerHTML=`<strong>${x.time} · ${x.direction} · ${x.confidence}%</strong><p>${x.market} · ${x.strategy}</p>`;ui.historialAnalisis.appendChild(a)});}

function explanationText(p){if(p.direction==="NO RECOMMENDED")return "Operación no recomendada. Los indicadores actuales no presentan suficiente coincidencia. Espera una mejor oportunidad.";const reason=p.reasons.slice(0,3).join(" ").replaceAll("Trend is bullish.","La tendencia es alcista.").replaceAll("Trend is bearish.","La tendencia es bajista.").replaceAll("Momentum is positive.","El momentum es positivo.").replaceAll("Momentum is negative.","El momentum es negativo.").replaceAll("Volatility is stable.","La volatilidad se mantiene estable.");return `Predicción ${p.direction}. ${reason} Confianza técnica ${p.confidence} por ciento. Tienes diez segundos para realizar la operación.`;}
function stopCountdown(){if(state.countdownTimer){clearInterval(state.countdownTimer);state.countdownTimer=null;}state.signalActive=false;refreshButtons();}
function startCountdown(){stopCountdown();state.signalActive=true;refreshButtons();const duration=CFG.countdown*1000;const start=performance.now();let lastSpoken=null;const tick=()=>{const elapsed=performance.now()-start;const remaining=Math.max(0,CFG.countdown-Math.floor(elapsed/1000));ui.cuentaRegresiva.textContent=String(remaining);if(remaining!==lastSpoken){lastSpoken=remaining;speak(String(remaining),{cancel:false,rate:1});}if(elapsed>=duration){stopCountdown();ui.cuentaRegresiva.textContent="0";ui.vigenciaSenal.textContent="Signal finished. You can generate a new signal.";ui.prediccionEstado.textContent="SIGNAL FINISHED";speak("Señal finalizada. Puedes generar una nueva señal.",{cancel:false});log("Signal countdown finished.","warning");}};tick();state.countdownTimer=setInterval(tick,100);}
function requestPrediction(){if(!state.connected||!state.engineOn||state.signalActive)return;updateEngine();const p=state.preparedPrediction||buildPrediction();renderPrediction(p);addHistory(p);log(`Prediction: ${p.direction} · ${p.confidence}%`,p.direction==="NO RECOMMENDED"?"warning":"success");if(p.direction==="NO RECOMMENDED"){speak(explanationText(p));return;}speak(explanationText(p),{onend:startCountdown});}

function formatPrice(price,pip){return Number.isFinite(price)?price.toFixed(Number.isInteger(pip)?pip:2):"--";}
function processTick(t){if(!t||!Number.isFinite(Number(t.precio)))return;if(t.simbolo&&t.simbolo!==state.symbol)return;const price=Number(t.precio),formatted=formatPrice(price,t.pipSize),digit=Number(formatted.replace(/\D/g,"").slice(-1));state.ticks++;state.prices.push(price);state.digits.push(digit);if(state.prices.length>CFG.maxTicks)state.prices.shift();if(state.digits.length>CFG.maxTicks)state.digits.shift();ui.precioActual.classList.remove("up","down");if(Number.isFinite(state.previousPrice)){if(price>state.previousPrice)ui.precioActual.classList.add("up");else if(price<state.previousPrice)ui.precioActual.classList.add("down");}state.previousPrice=price;state.pipSize=Number.isInteger(Number(t.pipSize))?Number(t.pipSize):state.pipSize;ui.precioActual.textContent=formatted;ui.contadorTicks.textContent=String(state.ticks);ui.ultimoDigito.textContent=Number.isInteger(digit)?String(digit):"--";ui.horaActualizacion.textContent=time(Number(t.epoch));ui.estadoDatos.textContent="LIVE";renderIndicators();updateEngine();renderProgress();}
function clearMarketData(){state.prices=[];state.digits=[];state.ticks=0;state.previousPrice=null;state.indicators=null;state.preparedPrediction=null;ui.precioActual.textContent="--";ui.precioActual.className="live-price";ui.contadorTicks.textContent="0";ui.ultimoDigito.textContent="--";ui.horaActualizacion.textContent="--";ui.estadoDatos.textContent=state.connected?"WAITING":"NO DATA";[ui.tendencia,ui.rsi,ui.momentum,ui.volatilidad].forEach(e=>e.textContent="--");[ui.detalleTendencia,ui.detalleRsi,ui.detalleMomentum,ui.detalleVolatilidad].forEach(e=>e.textContent="Waiting for data");resetSignal(state.engineOn?"The engine is preparing the new market.":"Connect and power the engine.");renderProgress();}

function connect(){syncSelection();if(state.connected||state.connecting)return;log("Opening Deriv connection.");speak("Conectando.");derivAPI.conectar(state.symbol);}
function disconnect(){stopCountdown();stopVoice();setEngine(false);derivAPI.desconectar();}
function toggleEngine(){if(!state.connected)return;if(state.engineOn){setEngine(false);speak("Herramienta apagada.");log("Engine powered off.","warning");}else{setEngine(true);updateEngine();renderProgress();speak("Herramienta encendida.");log("Engine powered on and analyzing in background.","success");}}
function changeMarket(){stopCountdown();syncSelection();clearMarketData();if(derivAPI.estaConectado())derivAPI.cambiarSimbolo(state.symbol);speak(`Mercado cambiado a ${state.market}.`);}
function changeStrategy(){stopCountdown();syncSelection();updateEngine();resetSignal("New strategy selected. Prediction is ready in background.");speak(`Estrategia cambiada a ${STRATEGY_NAMES[state.strategy]}.`);}
function changeMode(){stopCountdown();syncSelection();renderIndicators();updateEngine();resetSignal("Analysis mode changed. Prediction is ready in background.");}

derivAPI.al("estado",d=>{const s=d?.estado||"desconectado";if(s==="conectando"){setConnection("connecting","CONNECTING");ui.estadoDatos.textContent="CONNECTING";return;}if(s==="conectado"){setConnection("connected","CONNECTED");ui.estadoDatos.textContent="WAITING";log("Deriv connection established.","success");speak("Conectado.");return;}setConnection("offline","OFFLINE");setEngine(false);ui.estadoDatos.textContent="NO DATA";});
derivAPI.al("tick",processTick);
derivAPI.al("error",d=>{setConnection("error","ERROR");log(d?.mensaje||"Connection error.","error");speak("Se produjo un error de conexión.");});
derivAPI.al("diagnostico",d=>log(`[Deriv] ${d?.mensaje||"Diagnostic message."}`,d?.tipo==="exito"?"success":d?.tipo==="advertencia"?"warning":d?.tipo||"normal"));

function init(){syncSelection();populateVoices();window.speechSynthesis?.addEventListener?.("voiceschanged",populateVoices);updateVoiceUi();setConnection("offline","OFFLINE");setEngine(false);clearMarketData();ui.botonConectar.addEventListener("click",connect);ui.botonDesconectar.addEventListener("click",disconnect);ui.botonEncender.addEventListener("click",toggleEngine);ui.botonAnalizar.addEventListener("click",requestPrediction);ui.botonVoz.addEventListener("click",()=>{state.voiceOn=!state.voiceOn;stopVoice();updateVoiceUi();if(state.voiceOn)speak("Asistente de voz activado.");});ui.selectorIndice.addEventListener("change",changeMarket);ui.selectorOperacion.addEventListener("change",changeStrategy);ui.selectorModo.addEventListener("change",changeMode);ui.selectorVoz.addEventListener("change",()=>{state.selectedVoice=state.voices[Number(ui.selectorVoz.value)]||null;});[ui.velocidadVoz,ui.tonoVoz,ui.volumenVoz].forEach(e=>e.addEventListener("input",updateVoiceUi));ui.botonProbarVoz.addEventListener("click",()=>speak("Prueba de voz. El asistente está listo para anunciar tus predicciones."));ui.botonLimpiarHistorial.addEventListener("click",()=>{state.history=[];ui.historialAnalisis.innerHTML='<p class="empty">No predictions generated yet.</p>';});ui.botonLimpiarRegistro.addEventListener("click",()=>{ui.registroActividad.innerHTML="";});log(`Trading Analyzer V${CFG.version} loaded.`,"success");}
window.addEventListener("beforeunload",()=>{stopCountdown();stopVoice();derivAPI.desconectar();});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
