const URL_DERIV = "wss://api.derivws.com/trading/v1/options/ws/public";
const TIEMPO_RECONEXION = 3000;
const INTERVALO_PING = 30000;
const TIEMPO_MAXIMO_CONEXION = 12000;

export class DerivAPI {
  constructor(){this.socket=null;this.estado="desconectado";this.simboloActual="";this.idSuscripcion=null;this.cierreManual=false;this.temporizadorReconexion=null;this.temporizadorPing=null;this.temporizadorConexion=null;this.numeroSolicitud=0;this.eventos={estado:[],tick:[],error:[],diagnostico:[]};}
  al(tipo,fn){if(!this.eventos[tipo]||typeof fn!=="function")return;if(!this.eventos[tipo].includes(fn))this.eventos[tipo].push(fn)}
  emitir(tipo,datos={}){(this.eventos[tipo]||[]).forEach(fn=>{try{fn(datos)}catch(e){console.error("Error ejecutando evento:",tipo,e)}})}
  diagnostico(mensaje,tipo="normal"){this.emitir("diagnostico",{mensaje,tipo})}
  cambiarEstado(estado,texto=estado){this.estado=estado;this.emitir("estado",{estado,texto})}
  estaConectado(){return !!(this.socket&&this.socket.readyState===WebSocket.OPEN)}
  estaConectando(){return !!(this.socket&&this.socket.readyState===WebSocket.CONNECTING)}
  limpiarTemporizadorConexion(){if(this.temporizadorConexion){clearTimeout(this.temporizadorConexion);this.temporizadorConexion=null}}
  limpiarTemporizadorReconexion(){if(this.temporizadorReconexion){clearTimeout(this.temporizadorReconexion);this.temporizadorReconexion=null}}
  conectar(simbolo=this.simboloActual){const limpio=String(simbolo||"").trim();if(limpio)this.simboloActual=limpio;if(this.estaConectado()||this.estaConectando())return;this.cierreManual=false;this.limpiarTemporizadorReconexion();this.limpiarTemporizadorConexion();this.detenerPing();this.cambiarEstado("conectando","Conectando...");this.diagnostico("Abriendo conexión pública con Deriv.");try{this.socket=new WebSocket(URL_DERIV)}catch(e){this.socket=null;this.gestionarError("No se pudo crear la conexión: "+(e?.message||"error desconocido"));this.programarReconexion();return}const ws=this.socket;this.temporizadorConexion=setTimeout(()=>{if(this.socket===ws&&ws.readyState===WebSocket.CONNECTING){this.diagnostico("La conexión tardó demasiado y será reiniciada.","advertencia");try{ws.close()}catch{}}},TIEMPO_MAXIMO_CONEXION);ws.addEventListener("open",()=>{if(this.socket!==ws)return;this.limpiarTemporizadorConexion();this.cambiarEstado("conectado","Conectado");this.diagnostico("Conexión con Deriv establecida.","exito");this.iniciarPing();if(this.simboloActual)this.suscribirseTicks(this.simboloActual)});ws.addEventListener("message",e=>{if(this.socket===ws)this.procesarMensaje(e)});ws.addEventListener("error",()=>{if(this.socket===ws)this.gestionarError("La conexión WebSocket informó un error.")});ws.addEventListener("close",e=>{if(this.socket===ws)this.procesarCierre(e)})}
  procesarMensaje(evento){let d;try{d=JSON.parse(evento.data)}catch{this.gestionarError("Deriv envió una respuesta inválida.");return}if(d.error){this.gestionarError(d.error.message||d.error.code||"Error desconocido de Deriv");return}if(d.msg_type==="tick"&&d.tick){if(d.subscription?.id)this.idSuscripcion=d.subscription.id;const simbolo=String(d.tick.symbol||this.simboloActual||"").trim();if(simbolo&&this.simboloActual&&simbolo!==this.simboloActual)return;const precio=Number(d.tick.quote),epoch=Number(d.tick.epoch),pip=Number(d.tick.pip_size);if(!Number.isFinite(precio)){this.gestionarError("Deriv envió un precio no válido.");return}this.emitir("tick",{simbolo:simbolo||this.simboloActual,precio,epoch:Number.isFinite(epoch)?epoch:null,pipSize:Number.isInteger(pip)&&pip>=0?pip:null})}}
  procesarCierre(evento){this.limpiarTemporizadorConexion();this.detenerPing();this.socket=null;this.idSuscripcion=null;this.cambiarEstado("desconectado","Desconectado");if(this.cierreManual){this.diagnostico("La conexión fue cerrada manualmente.");return}this.diagnostico(`Conexión cerrada. Código: ${evento?.code??"desconocido"}. Intentando reconectar...`,"advertencia");this.programarReconexion()}
  programarReconexion(){if(this.cierreManual)return;this.limpiarTemporizadorReconexion();this.temporizadorReconexion=setTimeout(()=>{this.temporizadorReconexion=null;this.conectar(this.simboloActual)},TIEMPO_RECONEXION)}
  enviar(datos){if(!this.estaConectado())return false;try{this.socket.send(JSON.stringify(datos));return true}catch(e){this.gestionarError("No se pudo enviar la solicitud: "+(e?.message||"error desconocido"));return false}}
  siguienteSolicitud(){this.numeroSolicitud=this.numeroSolicitud>=999999?1:this.numeroSolicitud+1;return this.numeroSolicitud}
  cancelarSuscripcionActual(){if(!this.idSuscripcion||!this.estaConectado()){this.idSuscripcion=null;return false}const id=this.idSuscripcion;this.idSuscripcion=null;return this.enviar({forget:id,req_id:this.siguienteSolicitud()})}
  suscribirseTicks(simbolo){const limpio=String(simbolo||"").trim();if(!limpio){this.gestionarError("No se seleccionó un mercado válido.");return false}if(this.estaConectado()&&limpio===this.simboloActual&&this.idSuscripcion){this.diagnostico("El mercado seleccionado ya está activo.");return true}this.simboloActual=limpio;if(!this.estaConectado()){this.conectar(limpio);return true}this.cancelarSuscripcionActual();this.diagnostico("Solicitando precios de "+limpio+".");return this.enviar({ticks:limpio,subscribe:1,req_id:this.siguienteSolicitud()})}
  cambiarSimbolo(simbolo){return this.suscribirseTicks(simbolo)}
  iniciarPing(){this.detenerPing();this.temporizadorPing=setInterval(()=>{if(this.estaConectado())this.enviar({ping:1,req_id:this.siguienteSolicitud()})},INTERVALO_PING)}
  detenerPing(){if(this.temporizadorPing)clearInterval(this.temporizadorPing);this.temporizadorPing=null}
  desconectar(){this.cierreManual=true;this.limpiarTemporizadorReconexion();this.limpiarTemporizadorConexion();this.detenerPing();this.cancelarSuscripcionActual();const ws=this.socket;this.socket=null;this.idSuscripcion=null;if(ws){try{ws.close(1000,"Cierre manual")}catch{}}this.cambiarEstado("desconectado","Desconectado")}
  gestionarError(mensaje){const texto=String(mensaje||"Error desconocido de conexión.");this.emitir("error",{mensaje:texto});this.diagnostico(texto,"error")}
}
export const derivAPI=new DerivAPI();
